name: bs58check_dart
description: A straight forward implementation of base58check extending upon bs58 for Flutter writing in Dart.
version: 2.0.0+1
homepage: https://github.com/DeFiCh-WalletApp/bs58check-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  hex: ^0.2.0
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.0.0
